package jitems;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author ISAACELEAZAR
 */
public class Imagen extends javax.swing.JPanel {

    /**
     * Creates new form Imagen
     */
   
    public Imagen() {
        this.initComponents();
}
 
//Se crea un método cuyo parámetro debe ser un objeto Graphics
 
    @Override
    public void paint(Graphics grafico) {
        Dimension height = getSize();
 
        //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
 
        ImageIcon Img = new ImageIcon(getClass().getResource("/img/park.png")); 
 
        //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
 
        grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
 
        setOpaque(false);
        super.paintComponent(grafico);
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
