/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jitems;

import jitems.Jpiso_uno;
import javax.swing.JOptionPane;
import vehiculo.Ubicacion;
import vehiculo.Genera_vehiculo;

/**
 *
 * @author ISAACELEAZAR
 */
public class Jingreso_de_carros extends javax.swing.JFrame {
    
    Genera_vehiculo obj1= new Genera_vehiculo();
    Ubicacion obj2 = new Ubicacion();
    
    Jpiso_uno Opisouno = new Jpiso_uno();
    Jpiso_dos Opisodos = new Jpiso_dos();
    Jpiso_tres Opisotres = new Jpiso_tres();
    
    /**
     * Creates new form Jprincipal
     */
    public Jingreso_de_carros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        nuevo_carro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPlaca = new javax.swing.JTextPane();
        jSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMoto = new javax.swing.JButton();
        jCantidadCarros = new javax.swing.JButton();
        jCantidadMotos = new javax.swing.JButton();
        jPiso1 = new javax.swing.JButton();
        jPiso2 = new javax.swing.JButton();
        jPiso3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        choice1 = new java.awt.Choice();
        Ver_piso1 = new javax.swing.JButton();
        Ver_piso2 = new javax.swing.JButton();
        Ver_piso3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        totalCarros = new javax.swing.JMenuItem();
        totalMotos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        tVehiculos1 = new javax.swing.JMenuItem();
        cMoto1 = new javax.swing.JMenuItem();
        cCarro1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        tVehiculos2 = new javax.swing.JMenuItem();
        cMoto2 = new javax.swing.JMenuItem();
        cCarro2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        tVehiculos3 = new javax.swing.JMenuItem();
        cMoto3 = new javax.swing.JMenuItem();
        cCarro3 = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevo_carro.setText("Ingresar");
        nuevo_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_carroActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar un carro");

        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusLost(evt);
            }
        });

        jPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPlacaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jPlaca);

        jSalir.setForeground(new java.awt.Color(255, 0, 0));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresar una moto");

        jMoto.setText("Ingresar");
        jMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMotoActionPerformed(evt);
            }
        });

        jCantidadCarros.setText("Ver Cantidad Carros");
        jCantidadCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadCarrosActionPerformed(evt);
            }
        });

        jCantidadMotos.setText("Ver Cantidad Motos");
        jCantidadMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadMotosActionPerformed(evt);
            }
        });

        jPiso1.setText("Cantidad Piso 1");
        jPiso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPiso1ActionPerformed(evt);
            }
        });

        jPiso2.setText("Cantidad Piso 2");
        jPiso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPiso2ActionPerformed(evt);
            }
        });

        jPiso3.setText("Cantidad Piso 3");
        jPiso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPiso3ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Ver_piso1.setText("Piso 1");
        Ver_piso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_piso1ActionPerformed(evt);
            }
        });

        Ver_piso2.setText("Piso 2");
        Ver_piso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_piso2ActionPerformed(evt);
            }
        });

        Ver_piso3.setText("Piso 3");
        Ver_piso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ver_piso3ActionPerformed(evt);
            }
        });

        jMenu3.setText("Cantidad de Vehiculos");

        totalCarros.setText("Total Carros");
        jMenu3.add(totalCarros);

        totalMotos.setText("Total Motos");
        totalMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalMotosActionPerformed(evt);
            }
        });
        jMenu3.add(totalMotos);

        jMenu2.setText("Piso 1");

        tVehiculos1.setText("Vehiculos Total");
        jMenu2.add(tVehiculos1);

        cMoto1.setText("Cantidad Motos");
        jMenu2.add(cMoto1);

        cCarro1.setText("Cantidad Carros");
        cCarro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cCarro1ActionPerformed(evt);
            }
        });
        jMenu2.add(cCarro1);

        jMenu3.add(jMenu2);

        jMenu4.setText("Piso 2");

        tVehiculos2.setText("Total Vehiculos");
        jMenu4.add(tVehiculos2);

        cMoto2.setText("Cantidad Motos");
        jMenu4.add(cMoto2);

        cCarro2.setText("Cantidad Carros");
        jMenu4.add(cCarro2);

        jMenu3.add(jMenu4);

        jMenu5.setText("Piso 3");

        tVehiculos3.setText("Total Vehiculos");
        jMenu5.add(tVehiculos3);

        cMoto3.setText("Cantidad Motos");
        jMenu5.add(cMoto3);

        cCarro3.setText("Cantidad Carros");
        jMenu5.add(cCarro3);

        jMenu3.add(jMenu5);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nuevo_carro)
                            .addComponent(jMoto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCantidadCarros)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jCantidadMotos)
                                .addGap(38, 38, 38)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPiso1)
                            .addComponent(jPiso2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(Ver_piso1)
                        .addGap(18, 18, 18)
                        .addComponent(Ver_piso2)
                        .addGap(18, 18, 18)
                        .addComponent(Ver_piso3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSalir)
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jPiso3))))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nuevo_carro)
                    .addComponent(jCantidadCarros)
                    .addComponent(jPiso1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jMoto)
                        .addComponent(jPiso2)
                        .addComponent(jCantidadMotos)))
                .addGap(11, 11, 11)
                .addComponent(jPiso3)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSalir)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Ver_piso1)
                            .addComponent(Ver_piso2)
                            .addComponent(Ver_piso3))
                        .addGap(85, 85, 85))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_carroActionPerformed
        // TODO add your handling code here:
        System.out.println("Placa nueva");
        obj1.genera_placa();
        obj1.genera_hora();
        String fecha = obj1.get_fecha();
        String hora = obj1.get_hora();
        JOptionPane.showMessageDialog(this, "Fecha: "+ fecha + " Hora: "+hora,"VEHICULO INGRESADO", JOptionPane.OK_OPTION);
        
        String placa = new String();
        placa = obj1.pasa_placa();
        jPlaca.setText(placa+"\nCarro");
        obj2.genera_lugar(1);
        String posicion;
        posicion = obj2.get_posicion();
        
        jPlaca.setText(placa+"\nCarro"+"\nlugar: "+posicion);
    }//GEN-LAST:event_nuevo_carroActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMotoActionPerformed
        // TODO add your handling code here:
        System.out.println("\n\nPlaca nueva");
        obj1.genera_placa_moto();
        obj1.genera_hora();
        String fecha = obj1.get_fecha();
        String hora = obj1.get_hora();
        JOptionPane.showMessageDialog(this, "Fecha: "+ fecha + " Hora: "+hora,"VEHICULO INGRESADO", JOptionPane.OK_OPTION);
        String placa;
        placa = obj1.pasa_placa();
        jPlaca.setText(placa+"\nMoto");
        obj2.genera_lugar(2);
        String posicion;
        posicion = obj2.get_posicion();
        
        
        jPlaca.setText(placa+"\nMoto"+"\nlugar: "+posicion);
    }//GEN-LAST:event_jMotoActionPerformed

    private void jCantidadCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadCarrosActionPerformed
        // TODO add your handling code here:
        int n;
        n = obj1.cantidad_carros();
        JOptionPane.showMessageDialog(this, "Hay "+ n + " carro(s) en este momento.","", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jCantidadCarrosActionPerformed

    private void jCantidadMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadMotosActionPerformed
        // TODO add your handling code here:
        int n;
        n = obj1.cantidad_motos();
        JOptionPane.showMessageDialog(this, "Hay "+ n + " moto(s) en este momento.","", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jCantidadMotosActionPerformed

    private void jScrollPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1FocusLost

    private void jPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPlacaKeyPressed
        // TODO add your handling code here:
        jPlaca.setEnabled(false);
    }//GEN-LAST:event_jPlacaKeyPressed

    private void jPiso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPiso1ActionPerformed
        // TODO add your handling code here:
        int c1;
        c1 = obj2.get_cant1();
        JOptionPane.showMessageDialog(this, "Hay "+ c1 + " vehiculos en este momento.","PISO 1", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jPiso1ActionPerformed

    private void jPiso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPiso2ActionPerformed
        // TODO add your handling code here:
        int c2;
        c2 = obj2.get_cant2();
        JOptionPane.showMessageDialog(this, "Hay "+ c2 + " vehiculos en este momento.","PISO 2", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jPiso2ActionPerformed

    private void jPiso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPiso3ActionPerformed
        // TODO add your handling code here:
        int c3;
        c3 = obj2.get_cant3();
        JOptionPane.showMessageDialog(this, "Hay "+ c3 + " vehiculos en este momento.","PISO 3", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jPiso3ActionPerformed

    private void totalMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalMotosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalMotosActionPerformed

    private void cCarro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cCarro1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cCarro1ActionPerformed

    private void Ver_piso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_piso1ActionPerformed
        // TODO add your handling code here:
        Opisouno.setVisible(true);
        Opisouno.setLocationRelativeTo(null);
    }//GEN-LAST:event_Ver_piso1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Ver_piso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_piso2ActionPerformed
        // TODO add your handling code here:
        Opisodos.setVisible(true);
        Opisodos.setLocationRelativeTo(null);
    }//GEN-LAST:event_Ver_piso2ActionPerformed

    private void Ver_piso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ver_piso3ActionPerformed
        // TODO add your handling code here:
        Opisotres.setVisible(true);
        Opisotres.setLocationRelativeTo(null);
    }//GEN-LAST:event_Ver_piso3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jingreso_de_carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jingreso_de_carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jingreso_de_carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jingreso_de_carros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jingreso_de_carros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ver_piso1;
    private javax.swing.JButton Ver_piso2;
    private javax.swing.JButton Ver_piso3;
    private javax.swing.JMenuItem cCarro1;
    private javax.swing.JMenuItem cCarro2;
    private javax.swing.JMenuItem cCarro3;
    private javax.swing.JMenuItem cMoto1;
    private javax.swing.JMenuItem cMoto2;
    private javax.swing.JMenuItem cMoto3;
    private java.awt.Choice choice1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jCantidadCarros;
    private javax.swing.JButton jCantidadMotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jMoto;
    private javax.swing.JButton jPiso1;
    private javax.swing.JButton jPiso2;
    private javax.swing.JButton jPiso3;
    private javax.swing.JTextPane jPlaca;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo_carro;
    private javax.swing.JMenuItem tVehiculos1;
    private javax.swing.JMenuItem tVehiculos2;
    private javax.swing.JMenuItem tVehiculos3;
    private javax.swing.JMenuItem totalCarros;
    private javax.swing.JMenuItem totalMotos;
    // End of variables declaration//GEN-END:variables

    
}
