/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jitems;

/**
 *
 * @author USER
 */
public class Jpiso_tres extends javax.swing.JFrame {

    /**
     * Creates new form Jpiso_tres
     */
    public Jpiso_tres() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lc1 = new javax.swing.JLabel();
        Lc2 = new javax.swing.JLabel();
        Lc3 = new javax.swing.JLabel();
        Lc4 = new javax.swing.JLabel();
        Lc5 = new javax.swing.JLabel();
        Lc6 = new javax.swing.JLabel();
        Lc7 = new javax.swing.JLabel();
        Lc8 = new javax.swing.JLabel();
        Lc9 = new javax.swing.JLabel();
        Lc10 = new javax.swing.JLabel();
        Lc11 = new javax.swing.JLabel();
        Lc12 = new javax.swing.JLabel();
        Lc13 = new javax.swing.JLabel();
        Lc14 = new javax.swing.JLabel();
        Lc15 = new javax.swing.JLabel();
        Lc16 = new javax.swing.JLabel();
        Lc17 = new javax.swing.JLabel();
        Lc18 = new javax.swing.JLabel();
        Lc19 = new javax.swing.JLabel();
        Lc20 = new javax.swing.JLabel();
        Lc21 = new javax.swing.JLabel();
        Lc22 = new javax.swing.JLabel();
        Lc23 = new javax.swing.JLabel();
        Lc24 = new javax.swing.JLabel();
        Lc25 = new javax.swing.JLabel();
        Lc26 = new javax.swing.JLabel();
        Lc27 = new javax.swing.JLabel();
        Lc28 = new javax.swing.JLabel();
        Lc29 = new javax.swing.JLabel();
        Lc30 = new javax.swing.JLabel();
        Lc31 = new javax.swing.JLabel();
        Lc32 = new javax.swing.JLabel();
        Lc33 = new javax.swing.JLabel();
        Lc34 = new javax.swing.JLabel();
        Lc35 = new javax.swing.JLabel();
        Lc36 = new javax.swing.JLabel();
        Lc37 = new javax.swing.JLabel();
        Lc38 = new javax.swing.JLabel();
        Lc39 = new javax.swing.JLabel();
        Lc40 = new javax.swing.JLabel();
        Lc41 = new javax.swing.JLabel();
        Lc42 = new javax.swing.JLabel();
        Lc43 = new javax.swing.JLabel();
        Lc44 = new javax.swing.JLabel();
        Lc45 = new javax.swing.JLabel();
        Lc46 = new javax.swing.JLabel();
        Lc47 = new javax.swing.JLabel();
        Lc48 = new javax.swing.JLabel();
        Lc49 = new javax.swing.JLabel();
        Lc50 = new javax.swing.JLabel();
        Lpiso3 = new javax.swing.JLabel();
        Bsalir3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lc1.setForeground(new java.awt.Color(255, 0, 0));
        Lc1.setText("C1");

        Lc2.setForeground(new java.awt.Color(255, 0, 0));
        Lc2.setText("C2");

        Lc3.setForeground(new java.awt.Color(255, 0, 0));
        Lc3.setText("C3");

        Lc4.setForeground(new java.awt.Color(255, 0, 0));
        Lc4.setText("C4");

        Lc5.setForeground(new java.awt.Color(255, 0, 0));
        Lc5.setText("C5");

        Lc6.setForeground(new java.awt.Color(255, 0, 0));
        Lc6.setText("C6");

        Lc7.setForeground(new java.awt.Color(255, 0, 0));
        Lc7.setText("C7");

        Lc8.setForeground(new java.awt.Color(255, 0, 0));
        Lc8.setText("C8");

        Lc9.setForeground(new java.awt.Color(255, 0, 0));
        Lc9.setText("C9");

        Lc10.setForeground(new java.awt.Color(255, 0, 0));
        Lc10.setText("C10");

        Lc11.setForeground(new java.awt.Color(255, 0, 0));
        Lc11.setText("C11");

        Lc12.setForeground(new java.awt.Color(255, 0, 0));
        Lc12.setText("C12");

        Lc13.setForeground(new java.awt.Color(255, 0, 0));
        Lc13.setText("C13");

        Lc14.setForeground(new java.awt.Color(255, 0, 0));
        Lc14.setText("C14");

        Lc15.setForeground(new java.awt.Color(255, 0, 0));
        Lc15.setText("C15");

        Lc16.setForeground(new java.awt.Color(255, 0, 0));
        Lc16.setText("C16");

        Lc17.setForeground(new java.awt.Color(255, 0, 0));
        Lc17.setText("C17");

        Lc18.setForeground(new java.awt.Color(255, 0, 0));
        Lc18.setText("C18");

        Lc19.setForeground(new java.awt.Color(255, 0, 0));
        Lc19.setText("C19");

        Lc20.setForeground(new java.awt.Color(255, 0, 0));
        Lc20.setText("C20");

        Lc21.setForeground(new java.awt.Color(255, 0, 0));
        Lc21.setText("C21");

        Lc22.setForeground(new java.awt.Color(255, 0, 0));
        Lc22.setText("C22");

        Lc23.setForeground(new java.awt.Color(255, 0, 0));
        Lc23.setText("C23");

        Lc24.setForeground(new java.awt.Color(255, 0, 0));
        Lc24.setText("C24");

        Lc25.setForeground(new java.awt.Color(255, 0, 0));
        Lc25.setText("C25");

        Lc26.setForeground(new java.awt.Color(255, 0, 0));
        Lc26.setText("C26");

        Lc27.setForeground(new java.awt.Color(255, 0, 0));
        Lc27.setText("C27");

        Lc28.setForeground(new java.awt.Color(255, 0, 0));
        Lc28.setText("C28");

        Lc29.setForeground(new java.awt.Color(255, 0, 0));
        Lc29.setText("C29");

        Lc30.setForeground(new java.awt.Color(255, 0, 0));
        Lc30.setText("C30");

        Lc31.setForeground(new java.awt.Color(255, 0, 0));
        Lc31.setText("C31");

        Lc32.setForeground(new java.awt.Color(255, 0, 0));
        Lc32.setText("C32");

        Lc33.setForeground(new java.awt.Color(255, 0, 0));
        Lc33.setText("C33");

        Lc34.setForeground(new java.awt.Color(255, 0, 0));
        Lc34.setText("C34");

        Lc35.setForeground(new java.awt.Color(255, 0, 0));
        Lc35.setText("C35");

        Lc36.setForeground(new java.awt.Color(255, 0, 0));
        Lc36.setText("C36");

        Lc37.setForeground(new java.awt.Color(255, 0, 0));
        Lc37.setText("C37");

        Lc38.setForeground(new java.awt.Color(255, 0, 0));
        Lc38.setText("C38");

        Lc39.setForeground(new java.awt.Color(255, 0, 0));
        Lc39.setText("C39");

        Lc40.setForeground(new java.awt.Color(255, 0, 0));
        Lc40.setText("C40");

        Lc41.setForeground(new java.awt.Color(255, 0, 0));
        Lc41.setText("C41");

        Lc42.setForeground(new java.awt.Color(255, 0, 0));
        Lc42.setText("C42");

        Lc43.setForeground(new java.awt.Color(255, 0, 0));
        Lc43.setText("C43");

        Lc44.setForeground(new java.awt.Color(255, 0, 0));
        Lc44.setText("C44");

        Lc45.setForeground(new java.awt.Color(255, 0, 0));
        Lc45.setText("C45");

        Lc46.setForeground(new java.awt.Color(255, 0, 0));
        Lc46.setText("C46");

        Lc47.setForeground(new java.awt.Color(255, 0, 0));
        Lc47.setText("C47");

        Lc48.setForeground(new java.awt.Color(255, 0, 0));
        Lc48.setText("C48");

        Lc49.setForeground(new java.awt.Color(255, 0, 0));
        Lc49.setText("C49");

        Lc50.setForeground(new java.awt.Color(255, 0, 0));
        Lc50.setText("C50");

        Lpiso3.setText("PISO 3");

        Bsalir3.setText("Salir");
        Bsalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsalir3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lc21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lc30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lc31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lc40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lc1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lc11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lc41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lc44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lc45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lc49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Lc50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Bsalir3)
                                .addGap(201, 201, 201)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lpiso3)
                .addGap(220, 220, 220))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Lpiso3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lc1)
                    .addComponent(Lc2)
                    .addComponent(Lc3)
                    .addComponent(Lc4)
                    .addComponent(Lc5)
                    .addComponent(Lc6)
                    .addComponent(Lc7)
                    .addComponent(Lc8)
                    .addComponent(Lc9)
                    .addComponent(Lc10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lc11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lc12)
                        .addComponent(Lc13)
                        .addComponent(Lc14)
                        .addComponent(Lc15)
                        .addComponent(Lc16)
                        .addComponent(Lc17)
                        .addComponent(Lc18)
                        .addComponent(Lc19)
                        .addComponent(Lc20)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lc21)
                    .addComponent(Lc22)
                    .addComponent(Lc23)
                    .addComponent(Lc24)
                    .addComponent(Lc25)
                    .addComponent(Lc26)
                    .addComponent(Lc27)
                    .addComponent(Lc28)
                    .addComponent(Lc29)
                    .addComponent(Lc30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lc31)
                    .addComponent(Lc32)
                    .addComponent(Lc33)
                    .addComponent(Lc34)
                    .addComponent(Lc35)
                    .addComponent(Lc36)
                    .addComponent(Lc37)
                    .addComponent(Lc38)
                    .addComponent(Lc39)
                    .addComponent(Lc40))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lc41)
                    .addComponent(Lc42)
                    .addComponent(Lc43)
                    .addComponent(Lc44)
                    .addComponent(Lc45)
                    .addComponent(Lc46)
                    .addComponent(Lc47)
                    .addComponent(Lc48)
                    .addComponent(Lc49)
                    .addComponent(Lc50))
                .addGap(18, 18, 18)
                .addComponent(Bsalir3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bsalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsalir3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Bsalir3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jpiso_tres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jpiso_tres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jpiso_tres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jpiso_tres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jpiso_tres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsalir3;
    private javax.swing.JLabel Lc1;
    private javax.swing.JLabel Lc10;
    private javax.swing.JLabel Lc11;
    private javax.swing.JLabel Lc12;
    private javax.swing.JLabel Lc13;
    private javax.swing.JLabel Lc14;
    private javax.swing.JLabel Lc15;
    private javax.swing.JLabel Lc16;
    private javax.swing.JLabel Lc17;
    private javax.swing.JLabel Lc18;
    private javax.swing.JLabel Lc19;
    private javax.swing.JLabel Lc2;
    private javax.swing.JLabel Lc20;
    private javax.swing.JLabel Lc21;
    private javax.swing.JLabel Lc22;
    private javax.swing.JLabel Lc23;
    private javax.swing.JLabel Lc24;
    private javax.swing.JLabel Lc25;
    private javax.swing.JLabel Lc26;
    private javax.swing.JLabel Lc27;
    private javax.swing.JLabel Lc28;
    private javax.swing.JLabel Lc29;
    private javax.swing.JLabel Lc3;
    private javax.swing.JLabel Lc30;
    private javax.swing.JLabel Lc31;
    private javax.swing.JLabel Lc32;
    private javax.swing.JLabel Lc33;
    private javax.swing.JLabel Lc34;
    private javax.swing.JLabel Lc35;
    private javax.swing.JLabel Lc36;
    private javax.swing.JLabel Lc37;
    private javax.swing.JLabel Lc38;
    private javax.swing.JLabel Lc39;
    private javax.swing.JLabel Lc4;
    private javax.swing.JLabel Lc40;
    private javax.swing.JLabel Lc41;
    private javax.swing.JLabel Lc42;
    private javax.swing.JLabel Lc43;
    private javax.swing.JLabel Lc44;
    private javax.swing.JLabel Lc45;
    private javax.swing.JLabel Lc46;
    private javax.swing.JLabel Lc47;
    private javax.swing.JLabel Lc48;
    private javax.swing.JLabel Lc49;
    private javax.swing.JLabel Lc5;
    private javax.swing.JLabel Lc50;
    private javax.swing.JLabel Lc6;
    private javax.swing.JLabel Lc7;
    private javax.swing.JLabel Lc8;
    private javax.swing.JLabel Lc9;
    private javax.swing.JLabel Lpiso3;
    // End of variables declaration//GEN-END:variables
}
