/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jitems;

/**
 *
 * @author USER
 */
public class Jpiso_uno extends javax.swing.JFrame {

    /**
     * Creates new form Jpiso_uno
     */
    public Jpiso_uno() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        La1 = new javax.swing.JLabel();
        La2 = new javax.swing.JLabel();
        La3 = new javax.swing.JLabel();
        La4 = new javax.swing.JLabel();
        La5 = new javax.swing.JLabel();
        La6 = new javax.swing.JLabel();
        La7 = new javax.swing.JLabel();
        La8 = new javax.swing.JLabel();
        La9 = new javax.swing.JLabel();
        La10 = new javax.swing.JLabel();
        Lpiso1 = new javax.swing.JLabel();
        La11 = new javax.swing.JLabel();
        La12 = new javax.swing.JLabel();
        La13 = new javax.swing.JLabel();
        La14 = new javax.swing.JLabel();
        La15 = new javax.swing.JLabel();
        La16 = new javax.swing.JLabel();
        La17 = new javax.swing.JLabel();
        La18 = new javax.swing.JLabel();
        La19 = new javax.swing.JLabel();
        La20 = new javax.swing.JLabel();
        La21 = new javax.swing.JLabel();
        La22 = new javax.swing.JLabel();
        La23 = new javax.swing.JLabel();
        La24 = new javax.swing.JLabel();
        La25 = new javax.swing.JLabel();
        La26 = new javax.swing.JLabel();
        La27 = new javax.swing.JLabel();
        La28 = new javax.swing.JLabel();
        La29 = new javax.swing.JLabel();
        La30 = new javax.swing.JLabel();
        La31 = new javax.swing.JLabel();
        La32 = new javax.swing.JLabel();
        La33 = new javax.swing.JLabel();
        La34 = new javax.swing.JLabel();
        La35 = new javax.swing.JLabel();
        La36 = new javax.swing.JLabel();
        La37 = new javax.swing.JLabel();
        La38 = new javax.swing.JLabel();
        La39 = new javax.swing.JLabel();
        La40 = new javax.swing.JLabel();
        La41 = new javax.swing.JLabel();
        La42 = new javax.swing.JLabel();
        La43 = new javax.swing.JLabel();
        La44 = new javax.swing.JLabel();
        La45 = new javax.swing.JLabel();
        La46 = new javax.swing.JLabel();
        La47 = new javax.swing.JLabel();
        La48 = new javax.swing.JLabel();
        La49 = new javax.swing.JLabel();
        La50 = new javax.swing.JLabel();
        Bsalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        La1.setForeground(new java.awt.Color(255, 0, 0));
        La1.setText("A1");

        La2.setForeground(new java.awt.Color(255, 0, 0));
        La2.setText("A2");

        La3.setForeground(new java.awt.Color(255, 0, 0));
        La3.setText("A3");

        La4.setForeground(new java.awt.Color(255, 0, 0));
        La4.setText("A4");

        La5.setForeground(new java.awt.Color(255, 0, 0));
        La5.setText("A5");

        La6.setForeground(new java.awt.Color(255, 0, 0));
        La6.setText("A6");

        La7.setForeground(new java.awt.Color(255, 0, 0));
        La7.setText("A7");

        La8.setForeground(new java.awt.Color(255, 0, 0));
        La8.setText("A8");

        La9.setForeground(new java.awt.Color(255, 0, 0));
        La9.setText("A9");

        La10.setForeground(new java.awt.Color(255, 0, 0));
        La10.setText("A10");

        Lpiso1.setText("PISO 1");

        La11.setForeground(new java.awt.Color(255, 0, 0));
        La11.setText("A11");

        La12.setForeground(new java.awt.Color(255, 0, 0));
        La12.setText("A12");

        La13.setForeground(new java.awt.Color(255, 0, 0));
        La13.setText("A13");

        La14.setForeground(new java.awt.Color(255, 0, 0));
        La14.setText("A14");

        La15.setForeground(new java.awt.Color(255, 0, 0));
        La15.setText("A15");

        La16.setForeground(new java.awt.Color(255, 0, 0));
        La16.setText("A16");

        La17.setForeground(new java.awt.Color(255, 0, 0));
        La17.setText("A17");

        La18.setForeground(new java.awt.Color(255, 0, 0));
        La18.setText("A18");

        La19.setForeground(new java.awt.Color(255, 0, 0));
        La19.setText("A19");

        La20.setForeground(new java.awt.Color(255, 0, 0));
        La20.setText("A20");

        La21.setForeground(new java.awt.Color(255, 0, 0));
        La21.setText("A21");

        La22.setForeground(new java.awt.Color(255, 0, 0));
        La22.setText("A22");

        La23.setForeground(new java.awt.Color(255, 0, 0));
        La23.setText("A23");

        La24.setForeground(new java.awt.Color(255, 0, 0));
        La24.setText("A24");

        La25.setForeground(new java.awt.Color(255, 0, 0));
        La25.setText("A25");

        La26.setForeground(new java.awt.Color(255, 0, 0));
        La26.setText("A26");

        La27.setForeground(new java.awt.Color(255, 0, 0));
        La27.setText("A27");

        La28.setForeground(new java.awt.Color(255, 0, 0));
        La28.setText("A28");

        La29.setForeground(new java.awt.Color(255, 0, 0));
        La29.setText("A29");

        La30.setForeground(new java.awt.Color(255, 0, 0));
        La30.setText("A30");

        La31.setForeground(new java.awt.Color(255, 0, 0));
        La31.setText("A31");

        La32.setForeground(new java.awt.Color(255, 0, 0));
        La32.setText("A32");

        La33.setForeground(new java.awt.Color(255, 0, 0));
        La33.setText("A33");

        La34.setForeground(new java.awt.Color(255, 0, 0));
        La34.setText("A34");

        La35.setForeground(new java.awt.Color(255, 0, 0));
        La35.setText("A35");

        La36.setForeground(new java.awt.Color(255, 0, 0));
        La36.setText("A36");

        La37.setForeground(new java.awt.Color(255, 0, 0));
        La37.setText("A37");

        La38.setForeground(new java.awt.Color(255, 0, 0));
        La38.setText("A38");

        La39.setForeground(new java.awt.Color(255, 0, 0));
        La39.setText("A39");

        La40.setForeground(new java.awt.Color(255, 0, 0));
        La40.setText("A40");

        La41.setForeground(new java.awt.Color(255, 0, 0));
        La41.setText("A41");

        La42.setForeground(new java.awt.Color(255, 0, 0));
        La42.setText("A42");

        La43.setForeground(new java.awt.Color(255, 0, 0));
        La43.setText("A43");

        La44.setForeground(new java.awt.Color(255, 0, 0));
        La44.setText("A44");

        La45.setForeground(new java.awt.Color(255, 0, 0));
        La45.setText("A45");

        La46.setForeground(new java.awt.Color(255, 0, 0));
        La46.setText("A46");

        La47.setForeground(new java.awt.Color(255, 0, 0));
        La47.setText("A47");

        La48.setForeground(new java.awt.Color(255, 0, 0));
        La48.setText("A48");

        La49.setForeground(new java.awt.Color(255, 0, 0));
        La49.setText("A49");

        La50.setForeground(new java.awt.Color(255, 0, 0));
        La50.setText("A50");

        Bsalir.setText("Salir");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(La1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(Lpiso1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(La11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(La20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(La21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(La30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(La31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(La40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Bsalir)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(La41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(La42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(La43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(La44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(La45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(La46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(La47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(La49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(La50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(Lpiso1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La1)
                    .addComponent(La2)
                    .addComponent(La3)
                    .addComponent(La4)
                    .addComponent(La5)
                    .addComponent(La6)
                    .addComponent(La7)
                    .addComponent(La8)
                    .addComponent(La9)
                    .addComponent(La10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La11)
                    .addComponent(La12)
                    .addComponent(La13)
                    .addComponent(La14)
                    .addComponent(La15)
                    .addComponent(La16)
                    .addComponent(La17)
                    .addComponent(La18)
                    .addComponent(La19)
                    .addComponent(La20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La21)
                    .addComponent(La22)
                    .addComponent(La23)
                    .addComponent(La24)
                    .addComponent(La25)
                    .addComponent(La26)
                    .addComponent(La27)
                    .addComponent(La28)
                    .addComponent(La29)
                    .addComponent(La30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La31)
                    .addComponent(La32)
                    .addComponent(La33)
                    .addComponent(La34)
                    .addComponent(La35)
                    .addComponent(La36)
                    .addComponent(La37)
                    .addComponent(La38)
                    .addComponent(La39)
                    .addComponent(La40))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(La41)
                    .addComponent(La42)
                    .addComponent(La43)
                    .addComponent(La44)
                    .addComponent(La45)
                    .addComponent(La46)
                    .addComponent(La47)
                    .addComponent(La48)
                    .addComponent(La49)
                    .addComponent(La50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(Bsalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_BsalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jpiso_uno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jpiso_uno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jpiso_uno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jpiso_uno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jpiso_uno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsalir;
    private javax.swing.JLabel La1;
    private javax.swing.JLabel La10;
    private javax.swing.JLabel La11;
    private javax.swing.JLabel La12;
    private javax.swing.JLabel La13;
    private javax.swing.JLabel La14;
    private javax.swing.JLabel La15;
    private javax.swing.JLabel La16;
    private javax.swing.JLabel La17;
    private javax.swing.JLabel La18;
    private javax.swing.JLabel La19;
    private javax.swing.JLabel La2;
    private javax.swing.JLabel La20;
    private javax.swing.JLabel La21;
    private javax.swing.JLabel La22;
    private javax.swing.JLabel La23;
    private javax.swing.JLabel La24;
    private javax.swing.JLabel La25;
    private javax.swing.JLabel La26;
    private javax.swing.JLabel La27;
    private javax.swing.JLabel La28;
    private javax.swing.JLabel La29;
    private javax.swing.JLabel La3;
    private javax.swing.JLabel La30;
    private javax.swing.JLabel La31;
    private javax.swing.JLabel La32;
    private javax.swing.JLabel La33;
    private javax.swing.JLabel La34;
    private javax.swing.JLabel La35;
    private javax.swing.JLabel La36;
    private javax.swing.JLabel La37;
    private javax.swing.JLabel La38;
    private javax.swing.JLabel La39;
    private javax.swing.JLabel La4;
    private javax.swing.JLabel La40;
    private javax.swing.JLabel La41;
    private javax.swing.JLabel La42;
    private javax.swing.JLabel La43;
    private javax.swing.JLabel La44;
    private javax.swing.JLabel La45;
    private javax.swing.JLabel La46;
    private javax.swing.JLabel La47;
    private javax.swing.JLabel La48;
    private javax.swing.JLabel La49;
    private javax.swing.JLabel La5;
    private javax.swing.JLabel La50;
    private javax.swing.JLabel La6;
    private javax.swing.JLabel La7;
    private javax.swing.JLabel La8;
    private javax.swing.JLabel La9;
    private javax.swing.JLabel Lpiso1;
    // End of variables declaration//GEN-END:variables
}
