/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jitems;

/**
 *
 * @author USER
 */
public class Jpiso_dos extends javax.swing.JFrame {

    /**
     * Creates new form Jpiso_dos
     */
    public Jpiso_dos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lb1 = new javax.swing.JLabel();
        Lb2 = new javax.swing.JLabel();
        Lb3 = new javax.swing.JLabel();
        Lb4 = new javax.swing.JLabel();
        Lb5 = new javax.swing.JLabel();
        Lb6 = new javax.swing.JLabel();
        Lb7 = new javax.swing.JLabel();
        Lb8 = new javax.swing.JLabel();
        Lb9 = new javax.swing.JLabel();
        Lb10 = new javax.swing.JLabel();
        Lb11 = new javax.swing.JLabel();
        Lb12 = new javax.swing.JLabel();
        Lb13 = new javax.swing.JLabel();
        Lb14 = new javax.swing.JLabel();
        Lb15 = new javax.swing.JLabel();
        Lb16 = new javax.swing.JLabel();
        Lb17 = new javax.swing.JLabel();
        Lb18 = new javax.swing.JLabel();
        Lb19 = new javax.swing.JLabel();
        Lb20 = new javax.swing.JLabel();
        Lb21 = new javax.swing.JLabel();
        Lb22 = new javax.swing.JLabel();
        Lb23 = new javax.swing.JLabel();
        Lb24 = new javax.swing.JLabel();
        Lb25 = new javax.swing.JLabel();
        Lb26 = new javax.swing.JLabel();
        Lb27 = new javax.swing.JLabel();
        Lb28 = new javax.swing.JLabel();
        Lb29 = new javax.swing.JLabel();
        Lb30 = new javax.swing.JLabel();
        Lb31 = new javax.swing.JLabel();
        Lb32 = new javax.swing.JLabel();
        Lb33 = new javax.swing.JLabel();
        Lb34 = new javax.swing.JLabel();
        Lb35 = new javax.swing.JLabel();
        Lb36 = new javax.swing.JLabel();
        Lb37 = new javax.swing.JLabel();
        Lb38 = new javax.swing.JLabel();
        Lb39 = new javax.swing.JLabel();
        Lb40 = new javax.swing.JLabel();
        Lb41 = new javax.swing.JLabel();
        Lb42 = new javax.swing.JLabel();
        Lb43 = new javax.swing.JLabel();
        Lb44 = new javax.swing.JLabel();
        Lb45 = new javax.swing.JLabel();
        Lb46 = new javax.swing.JLabel();
        Lb47 = new javax.swing.JLabel();
        Lb48 = new javax.swing.JLabel();
        Lb49 = new javax.swing.JLabel();
        Lb50 = new javax.swing.JLabel();
        Lpiso2 = new javax.swing.JLabel();
        Bsalir2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Lb1.setForeground(new java.awt.Color(255, 0, 0));
        Lb1.setText("B1");

        Lb2.setForeground(new java.awt.Color(255, 0, 0));
        Lb2.setText("B2");

        Lb3.setForeground(new java.awt.Color(255, 0, 0));
        Lb3.setText("B3");

        Lb4.setForeground(new java.awt.Color(255, 0, 0));
        Lb4.setText("B4");

        Lb5.setForeground(new java.awt.Color(255, 0, 0));
        Lb5.setText("B5");

        Lb6.setForeground(new java.awt.Color(255, 0, 0));
        Lb6.setText("B6");

        Lb7.setForeground(new java.awt.Color(255, 0, 0));
        Lb7.setText("B7");

        Lb8.setForeground(new java.awt.Color(255, 0, 0));
        Lb8.setText("B8");

        Lb9.setForeground(new java.awt.Color(255, 0, 0));
        Lb9.setText("B9");

        Lb10.setForeground(new java.awt.Color(255, 0, 0));
        Lb10.setText("B10");

        Lb11.setForeground(new java.awt.Color(255, 0, 0));
        Lb11.setText("B11");

        Lb12.setForeground(new java.awt.Color(255, 0, 0));
        Lb12.setText("B12");

        Lb13.setForeground(new java.awt.Color(255, 0, 0));
        Lb13.setText("B13");

        Lb14.setForeground(new java.awt.Color(255, 0, 0));
        Lb14.setText("B14");

        Lb15.setForeground(new java.awt.Color(255, 0, 0));
        Lb15.setText("B15");

        Lb16.setForeground(new java.awt.Color(255, 0, 0));
        Lb16.setText("B16");

        Lb17.setForeground(new java.awt.Color(255, 0, 0));
        Lb17.setText("B17");

        Lb18.setForeground(new java.awt.Color(255, 0, 0));
        Lb18.setText("B18");

        Lb19.setForeground(new java.awt.Color(255, 0, 0));
        Lb19.setText("B19");

        Lb20.setForeground(new java.awt.Color(255, 0, 0));
        Lb20.setText("B20");

        Lb21.setForeground(new java.awt.Color(255, 0, 0));
        Lb21.setText("B21");

        Lb22.setForeground(new java.awt.Color(255, 0, 0));
        Lb22.setText("B22");

        Lb23.setForeground(new java.awt.Color(255, 0, 0));
        Lb23.setText("B23");

        Lb24.setForeground(new java.awt.Color(255, 0, 0));
        Lb24.setText("B24");

        Lb25.setForeground(new java.awt.Color(255, 0, 0));
        Lb25.setText("B25");

        Lb26.setForeground(new java.awt.Color(255, 0, 0));
        Lb26.setText("B26");

        Lb27.setForeground(new java.awt.Color(255, 0, 0));
        Lb27.setText("B27");

        Lb28.setForeground(new java.awt.Color(255, 0, 0));
        Lb28.setText("B28");

        Lb29.setForeground(new java.awt.Color(255, 0, 0));
        Lb29.setText("B29");

        Lb30.setForeground(new java.awt.Color(255, 0, 0));
        Lb30.setText("B30");

        Lb31.setForeground(new java.awt.Color(255, 0, 0));
        Lb31.setText("B31");

        Lb32.setForeground(new java.awt.Color(255, 0, 0));
        Lb32.setText("B32");

        Lb33.setForeground(new java.awt.Color(255, 0, 0));
        Lb33.setText("B33");

        Lb34.setForeground(new java.awt.Color(255, 0, 0));
        Lb34.setText("B34");

        Lb35.setForeground(new java.awt.Color(255, 0, 0));
        Lb35.setText("B35");

        Lb36.setForeground(new java.awt.Color(255, 0, 0));
        Lb36.setText("B36");

        Lb37.setForeground(new java.awt.Color(255, 0, 0));
        Lb37.setText("B37");

        Lb38.setForeground(new java.awt.Color(255, 0, 0));
        Lb38.setText("B38");

        Lb39.setForeground(new java.awt.Color(255, 0, 0));
        Lb39.setText("B39");

        Lb40.setForeground(new java.awt.Color(255, 0, 0));
        Lb40.setText("B40");

        Lb41.setForeground(new java.awt.Color(255, 0, 0));
        Lb41.setText("B41");

        Lb42.setForeground(new java.awt.Color(255, 0, 0));
        Lb42.setText("B42");

        Lb43.setForeground(new java.awt.Color(255, 0, 0));
        Lb43.setText("B43");

        Lb44.setForeground(new java.awt.Color(255, 0, 0));
        Lb44.setText("B44");

        Lb45.setForeground(new java.awt.Color(255, 0, 0));
        Lb45.setText("B45");

        Lb46.setForeground(new java.awt.Color(255, 0, 0));
        Lb46.setText("B46");

        Lb47.setForeground(new java.awt.Color(255, 0, 0));
        Lb47.setText("B47");

        Lb48.setForeground(new java.awt.Color(255, 0, 0));
        Lb48.setText("B48");

        Lb49.setForeground(new java.awt.Color(255, 0, 0));
        Lb49.setText("B49");

        Lb50.setForeground(new java.awt.Color(255, 0, 0));
        Lb50.setText("B50");

        Lpiso2.setText("PISO 2");

        Bsalir2.setText("Salir");
        Bsalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bsalir2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lb11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lb20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Lb21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Lb29, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Lb30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lb31, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb32, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb33, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb34, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb35, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb36, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb37, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb38, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb39, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb40, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Lb41, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb42, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb43, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lb44, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Lb45, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lb46, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lb47, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lb48, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lb49, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Lb50, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(Bsalir2)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addComponent(Lpiso2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lpiso2)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb1)
                    .addComponent(Lb2)
                    .addComponent(Lb3)
                    .addComponent(Lb4)
                    .addComponent(Lb5)
                    .addComponent(Lb6)
                    .addComponent(Lb7)
                    .addComponent(Lb8)
                    .addComponent(Lb9)
                    .addComponent(Lb10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb11)
                    .addComponent(Lb12)
                    .addComponent(Lb13)
                    .addComponent(Lb14)
                    .addComponent(Lb15)
                    .addComponent(Lb16)
                    .addComponent(Lb17)
                    .addComponent(Lb18)
                    .addComponent(Lb19)
                    .addComponent(Lb20))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lb21)
                    .addComponent(Lb22)
                    .addComponent(Lb23)
                    .addComponent(Lb24)
                    .addComponent(Lb26)
                    .addComponent(Lb27)
                    .addComponent(Lb25)
                    .addComponent(Lb28)
                    .addComponent(Lb29)
                    .addComponent(Lb30))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb31, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lb32)
                        .addComponent(Lb33)
                        .addComponent(Lb34)
                        .addComponent(Lb35)
                        .addComponent(Lb36)
                        .addComponent(Lb37)
                        .addComponent(Lb38)
                        .addComponent(Lb39)
                        .addComponent(Lb40)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lb50, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lb41)
                        .addComponent(Lb42)
                        .addComponent(Lb43)
                        .addComponent(Lb44)
                        .addComponent(Lb45)
                        .addComponent(Lb46)
                        .addComponent(Lb47)
                        .addComponent(Lb48)
                        .addComponent(Lb49)))
                .addGap(18, 18, 18)
                .addComponent(Bsalir2)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bsalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bsalir2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Bsalir2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jpiso_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jpiso_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jpiso_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jpiso_dos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jpiso_dos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bsalir2;
    private javax.swing.JLabel Lb1;
    private javax.swing.JLabel Lb10;
    private javax.swing.JLabel Lb11;
    private javax.swing.JLabel Lb12;
    private javax.swing.JLabel Lb13;
    private javax.swing.JLabel Lb14;
    private javax.swing.JLabel Lb15;
    private javax.swing.JLabel Lb16;
    private javax.swing.JLabel Lb17;
    private javax.swing.JLabel Lb18;
    private javax.swing.JLabel Lb19;
    private javax.swing.JLabel Lb2;
    private javax.swing.JLabel Lb20;
    private javax.swing.JLabel Lb21;
    private javax.swing.JLabel Lb22;
    private javax.swing.JLabel Lb23;
    private javax.swing.JLabel Lb24;
    private javax.swing.JLabel Lb25;
    private javax.swing.JLabel Lb26;
    private javax.swing.JLabel Lb27;
    private javax.swing.JLabel Lb28;
    private javax.swing.JLabel Lb29;
    private javax.swing.JLabel Lb3;
    private javax.swing.JLabel Lb30;
    private javax.swing.JLabel Lb31;
    private javax.swing.JLabel Lb32;
    private javax.swing.JLabel Lb33;
    private javax.swing.JLabel Lb34;
    private javax.swing.JLabel Lb35;
    private javax.swing.JLabel Lb36;
    private javax.swing.JLabel Lb37;
    private javax.swing.JLabel Lb38;
    private javax.swing.JLabel Lb39;
    private javax.swing.JLabel Lb4;
    private javax.swing.JLabel Lb40;
    private javax.swing.JLabel Lb41;
    private javax.swing.JLabel Lb42;
    private javax.swing.JLabel Lb43;
    private javax.swing.JLabel Lb44;
    private javax.swing.JLabel Lb45;
    private javax.swing.JLabel Lb46;
    private javax.swing.JLabel Lb47;
    private javax.swing.JLabel Lb48;
    private javax.swing.JLabel Lb49;
    private javax.swing.JLabel Lb5;
    private javax.swing.JLabel Lb50;
    private javax.swing.JLabel Lb6;
    private javax.swing.JLabel Lb7;
    private javax.swing.JLabel Lb8;
    private javax.swing.JLabel Lb9;
    private javax.swing.JLabel Lpiso2;
    // End of variables declaration//GEN-END:variables
}
