/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jitems;

import javax.swing.JOptionPane;
import placas.Vehiculo;

/**
 *
 * @author ISAACELEAZAR
 */
public class Jprincipal extends javax.swing.JFrame {
    
    Vehiculo obj1= new Vehiculo();
    /**
     * Creates new form Jprincipal
     */
    public Jprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nuevo_carro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPlaca = new javax.swing.JTextPane();
        jSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMoto = new javax.swing.JButton();
        jCantidadCarros = new javax.swing.JButton();
        jCantidadMotos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nuevo_carro.setText("Ingresar");
        nuevo_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevo_carroActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingresar un carro");

        jScrollPane1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jScrollPane1FocusLost(evt);
            }
        });

        jPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPlacaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jPlaca);

        jSalir.setForeground(new java.awt.Color(255, 0, 0));
        jSalir.setText("Salir");
        jSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSalirActionPerformed(evt);
            }
        });

        jLabel2.setText("Ingresar una moto");

        jMoto.setText("Ingresar");
        jMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMotoActionPerformed(evt);
            }
        });

        jCantidadCarros.setText("Cantidad Carros");
        jCantidadCarros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadCarrosActionPerformed(evt);
            }
        });

        jCantidadMotos.setText("Cantidad Motos");
        jCantidadMotos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCantidadMotosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSalir)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jMoto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCantidadMotos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nuevo_carro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                                .addComponent(jCantidadCarros))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevo_carro)
                    .addComponent(jLabel1)
                    .addComponent(jCantidadCarros))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jMoto)
                    .addComponent(jCantidadMotos))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSalir)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevo_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevo_carroActionPerformed
        // TODO add your handling code here:
        System.out.println("Placa nueva");
        obj1.genera_placa();
        String placa = new String();
        placa = obj1.pasa_placa();
        jPlaca.setText(placa+"\nCarro");
        
    }//GEN-LAST:event_nuevo_carroActionPerformed

    private void jSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jSalirActionPerformed

    private void jMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMotoActionPerformed
        // TODO add your handling code here:
        System.out.println("Placa nueva");
        obj1.genera_placa_moto();
        String placa;
        placa = obj1.pasa_placa();
        jPlaca.setText(placa+"\nMoto");
    }//GEN-LAST:event_jMotoActionPerformed

    private void jCantidadCarrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadCarrosActionPerformed
        // TODO add your handling code here:
        int n;
        n = obj1.cantidad_carros();
        JOptionPane.showMessageDialog(this, "Hay "+ n + " carro(s) en este momento.","", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jCantidadCarrosActionPerformed

    private void jCantidadMotosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCantidadMotosActionPerformed
        // TODO add your handling code here:
        int n;
        n = obj1.cantidad_motos();
        JOptionPane.showMessageDialog(this, "Hay "+ n + " moto(s) en este momento.","", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jCantidadMotosActionPerformed

    private void jScrollPane1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jScrollPane1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1FocusLost

    private void jPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPlacaKeyPressed
        // TODO add your handling code here:
        jPlaca.setEnabled(false);
    }//GEN-LAST:event_jPlacaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCantidadCarros;
    private javax.swing.JButton jCantidadMotos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jMoto;
    private javax.swing.JTextPane jPlaca;
    private javax.swing.JButton jSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevo_carro;
    // End of variables declaration//GEN-END:variables

    
}
