package jitems;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLDataException;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import vehiculo.Cliente;

/**
 *
 * @author ISAACELEAZAR
 */
public final class Vista_Datos extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Datos
     */
    Connection con=null;
    Statement stmt=null;
    ResultSet rs=null;
    Cliente nuevo1 ;
    List<Cliente> lcliente= new ArrayList<Cliente>();
    
    public Vista_Datos(Connection con_, Statement stmt_) {
        initComponents();
        this.con=con_;
        this.stmt= stmt_;
        this.traeClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCliente = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jTabbedPane1.setBackground(java.awt.Color.darkGray);

        jPanel1.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Vehiculos Ahora", jPanel1);

        jPanel2.setBackground(java.awt.Color.darkGray);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Lista de Vehiculos", jPanel2);

        jPanel3.setBackground(java.awt.Color.darkGray);

        tCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tCliente);

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setForeground(new java.awt.Color(51, 51, 0));
        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Clientes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void traeClientes(){
           String qry = "SELECT * FROM cliente;";
        try{
           rs=stmt.executeQuery(qry);
                     
        }catch(SQLDataException e){
            System.out.printf("Error en la consulta.");
        } catch (SQLException ex) {
            Logger.getLogger(J_cobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            while(rs.next()){
                 nuevo1 = new Cliente(rs.getInt("cedula"),rs.getString("nombre"),rs.getString("placa"));
                 lcliente.add(nuevo1);
                 
                 //System.out.println("Ultimo id:"+this.idVal);
            }
        } catch (SQLException ex) {
            Logger.getLogger(J_cobrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(int i =0; i<lcliente.size(); i++)
        System.out.println("Cliente :"+lcliente.get(i).getNombre()+"Placa:"+lcliente.get(i).getPlaca());
    }
    
    public void limpiarTabla(int se){
        DefaultTableModel tb = (DefaultTableModel) tCliente.getModel();
        //DefaultTableModel tb2 = (DefaultTableModel) jTable2.getModel();
        //DefaultTableModel tb3 = (DefaultTableModel) jTable3.getModel();
        //DefaultTableModel tb4 = (DefaultTableModel) jTable4.getModel();
        //int g = jTable2.getRowCount()-1;
        int f = tCliente.getRowCount()-1;
        //int ff = jTable3.getRowCount()-1;
        //int hh = jTable4.getRowCount()-1;
        for (int i = f; i >= 0; i--) {
                    tb.removeRow(tb.getRowCount()-1);}
        /*switch (se) {
            case 1:
                for (int i = f; i >= 0; i--) {
                    tb.removeRow(tb.getRowCount()-1);
                }       break;
            case 2:
                for(int h = g; h >=0; h--){
                    tb2.removeRow(tb2.getRowCount()-1);
                }       break;
            case 3:
                for(int h1 = ff;h1>=0;h1--){
                    tb3.removeRow(tb3.getRowCount()-1);
                }
                break;
            case 4:
                for(int h2 = hh;h2>=0;h2--){
                    tb4.removeRow(tb4.getRowCount()-1);
                }
                break;
            default:
                break;
        }*/
        
    }
    
     public void llenarTabla(){
        this.limpiarTabla(0);
        int i;
        tCliente.getColumnModel();
        DefaultTableModel model = (DefaultTableModel)tCliente.getModel();
        
        for(i = 0; i<lcliente.size();i++){
        model.addRow(new Object[]{
           lcliente.get(i).getCedula(),lcliente.get(i).getNombre(),lcliente.get(i).getPlaca()});
    }
    
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               
        this.llenarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        lcliente.clear();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tCliente;
    // End of variables declaration//GEN-END:variables
}
